This is makeindex, version 2.18 [TeX Live 2026] (kpathsea + Thai support).
Scanning style file ./tcc.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file tcc.acn....done (74 entries accepted, 0 rejected).
Sorting entries....done (469 comparisons).
Generating output file tcc.acr....done (43 lines written, 0 warnings).
Output written in tcc.acr.
Transcript written in tcc.alg.
